version: "3.8"
services:    
    scr-be:
        container_name: api-scr
        image: scr-be
        build:
            context: .
            args:
                PORT: ${BE_PORT}
        ports:
            - ${BE_PORT}:3000
        networks:
            - scr-network
        restart: unless-stopped
        depends_on:
            - mongodb
        env_file:
            - ./.env
        volumes:
            - ./:/urs/src/app
            - node-modules-volume:/urs/src/app/node_modules
    mongodb:
        container_name: database-scr
        image: mongo:latest
        ports:
            - ${DB_PORT}:27017
        networks:
            - scr-network
        restart: always
        env_file:
            - ./.env
        volumes:
            - ./mongo-entrypoint:/docker-entrypoint-initdb.d
        entrypoint:
            - bash
            - -c
            - |
                chmod +x /docker-entrypoint-initdb.d/mongo-init.sh
                exec /docker-entrypoint-initdb.d/mongo-init.sh
volumes:
    node-modules-volume:
networks:
    scr-network:
        driver: bridge