version: "3.8"
services:    
    scr-be:
        container_name: api-scr
        image: scr-be
        build:
            context: .
            args:
                PORT: ${BE_PORT}
        ports:
            - ${BE_PORT}:3000
        networks:
            - scr-network
        restart: unless-stopped
        depends_on:
            - mongodb
        env_file:
            - ./.env
        volumes:
            - ./:/urs/src/app
            - node-modules-volume:/urs/src/app/node_modules
    mongodb:
        container_name: database-scr
        image: mongo:4.4.10
        ports:
            - ${DB_PORT}:27017
        networks:
            - scr-network
        restart: always
        env_file:
            - ./.env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${INIT_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${INIT_DB_PASSWORD}
        volumes:
            - ./mongo-entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
    node-modules-volume:
networks:
    scr-network:
        driver: bridge